// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package stage

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	nintendo2 "telegram-splatoon2-bot/service/nintendo"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson1870c743DecodeTelegramSplatoon2BotServiceRepositoryStage(in *jlexer.Lexer, out *stageCollection) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
	} else {
		in.Delim('{')
		*out = make(stageCollection)
		for !in.IsDelim('}') {
			key := string(in.String())
			in.WantColon()
			var v1 *nintendo2.Stage
			if in.IsNull() {
				in.Skip()
				v1 = nil
			} else {
				if v1 == nil {
					v1 = new(nintendo2.Stage)
				}
				(*v1).UnmarshalEasyJSON(in)
			}
			(*out)[key] = v1
			in.WantComma()
		}
		in.Delim('}')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1870c743EncodeTelegramSplatoon2BotServiceRepositoryStage(out *jwriter.Writer, in stageCollection) {
	if in == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
		out.RawString(`null`)
	} else {
		out.RawByte('{')
		v2First := true
		for v2Name, v2Value := range in {
			if v2First {
				v2First = false
			} else {
				out.RawByte(',')
			}
			out.String(string(v2Name))
			out.RawByte(':')
			if v2Value == nil {
				out.RawString("null")
			} else {
				(*v2Value).MarshalEasyJSON(out)
			}
		}
		out.RawByte('}')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v stageCollection) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1870c743EncodeTelegramSplatoon2BotServiceRepositoryStage(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v stageCollection) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1870c743EncodeTelegramSplatoon2BotServiceRepositoryStage(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *stageCollection) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1870c743DecodeTelegramSplatoon2BotServiceRepositoryStage(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *stageCollection) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1870c743DecodeTelegramSplatoon2BotServiceRepositoryStage(l, v)
}
