// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package salmon

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	nintendo "telegram-splatoon2-bot/service/nintendo"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson1870c743DecodeTelegramSplatoon2BotServiceRepositorySalmon(in *jlexer.Lexer, out *weaponCollection) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
	} else {
		in.Delim('{')
		*out = make(weaponCollection)
		for !in.IsDelim('}') {
			key := string(in.String())
			in.WantColon()
			var v1 nintendo.SalmonWeaponType
			easyjson1870c743DecodeTelegramSplatoon2BotServiceNintendo(in, &v1)
			(*out)[key] = v1
			in.WantComma()
		}
		in.Delim('}')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1870c743EncodeTelegramSplatoon2BotServiceRepositorySalmon(out *jwriter.Writer, in weaponCollection) {
	if in == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
		out.RawString(`null`)
	} else {
		out.RawByte('{')
		v2First := true
		for v2Name, v2Value := range in {
			if v2First {
				v2First = false
			} else {
				out.RawByte(',')
			}
			out.String(string(v2Name))
			out.RawByte(':')
			easyjson1870c743EncodeTelegramSplatoon2BotServiceNintendo(out, v2Value)
		}
		out.RawByte('}')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v weaponCollection) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1870c743EncodeTelegramSplatoon2BotServiceRepositorySalmon(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v weaponCollection) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1870c743EncodeTelegramSplatoon2BotServiceRepositorySalmon(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *weaponCollection) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1870c743DecodeTelegramSplatoon2BotServiceRepositorySalmon(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *weaponCollection) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1870c743DecodeTelegramSplatoon2BotServiceRepositorySalmon(l, v)
}
func easyjson1870c743DecodeTelegramSplatoon2BotServiceNintendo(in *jlexer.Lexer, out *nintendo.SalmonWeaponType) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "weapon":
			if in.IsNull() {
				in.Skip()
				out.Weapon = nil
			} else {
				if out.Weapon == nil {
					out.Weapon = new(nintendo.SalmonWeapon)
				}
				easyjson1870c743DecodeTelegramSplatoon2BotServiceNintendo1(in, out.Weapon)
			}
		case "coop_special_weapon":
			if in.IsNull() {
				in.Skip()
				out.SpecialWeapon = nil
			} else {
				if out.SpecialWeapon == nil {
					out.SpecialWeapon = new(nintendo.SalmonSpecialWeapon)
				}
				easyjson1870c743DecodeTelegramSplatoon2BotServiceNintendo2(in, out.SpecialWeapon)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1870c743EncodeTelegramSplatoon2BotServiceNintendo(out *jwriter.Writer, in nintendo.SalmonWeaponType) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"weapon\":"
		out.RawString(prefix)
		if in.Weapon == nil {
			out.RawString("null")
		} else {
			easyjson1870c743EncodeTelegramSplatoon2BotServiceNintendo1(out, *in.Weapon)
		}
	}
	{
		const prefix string = ",\"coop_special_weapon\":"
		out.RawString(prefix)
		if in.SpecialWeapon == nil {
			out.RawString("null")
		} else {
			easyjson1870c743EncodeTelegramSplatoon2BotServiceNintendo2(out, *in.SpecialWeapon)
		}
	}
	out.RawByte('}')
}
func easyjson1870c743DecodeTelegramSplatoon2BotServiceNintendo2(in *jlexer.Lexer, out *nintendo.SalmonSpecialWeapon) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "image":
			out.Image = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1870c743EncodeTelegramSplatoon2BotServiceNintendo2(out *jwriter.Writer, in nintendo.SalmonSpecialWeapon) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"image\":"
		out.RawString(prefix)
		out.String(string(in.Image))
	}
	out.RawByte('}')
}
func easyjson1870c743DecodeTelegramSplatoon2BotServiceNintendo1(in *jlexer.Lexer, out *nintendo.SalmonWeapon) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "name":
			out.Name = string(in.String())
		case "image":
			out.Image = string(in.String())
		case "thumbnail":
			out.Thumbnail = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1870c743EncodeTelegramSplatoon2BotServiceNintendo1(out *jwriter.Writer, in nintendo.SalmonWeapon) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"image\":"
		out.RawString(prefix)
		out.String(string(in.Image))
	}
	{
		const prefix string = ",\"thumbnail\":"
		out.RawString(prefix)
		out.String(string(in.Thumbnail))
	}
	out.RawByte('}')
}
func easyjson1870c743DecodeTelegramSplatoon2BotServiceRepositorySalmon1(in *jlexer.Lexer, out *stageCollection) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
	} else {
		in.Delim('{')
		*out = make(stageCollection)
		for !in.IsDelim('}') {
			key := string(in.String())
			in.WantColon()
			var v3 nintendo.SalmonStage
			easyjson1870c743DecodeTelegramSplatoon2BotServiceNintendo3(in, &v3)
			(*out)[key] = v3
			in.WantComma()
		}
		in.Delim('}')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1870c743EncodeTelegramSplatoon2BotServiceRepositorySalmon1(out *jwriter.Writer, in stageCollection) {
	if in == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
		out.RawString(`null`)
	} else {
		out.RawByte('{')
		v4First := true
		for v4Name, v4Value := range in {
			if v4First {
				v4First = false
			} else {
				out.RawByte(',')
			}
			out.String(string(v4Name))
			out.RawByte(':')
			easyjson1870c743EncodeTelegramSplatoon2BotServiceNintendo3(out, v4Value)
		}
		out.RawByte('}')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v stageCollection) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1870c743EncodeTelegramSplatoon2BotServiceRepositorySalmon1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v stageCollection) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1870c743EncodeTelegramSplatoon2BotServiceRepositorySalmon1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *stageCollection) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1870c743DecodeTelegramSplatoon2BotServiceRepositorySalmon1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *stageCollection) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1870c743DecodeTelegramSplatoon2BotServiceRepositorySalmon1(l, v)
}
func easyjson1870c743DecodeTelegramSplatoon2BotServiceNintendo3(in *jlexer.Lexer, out *nintendo.SalmonStage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "image":
			out.Image = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1870c743EncodeTelegramSplatoon2BotServiceNintendo3(out *jwriter.Writer, in nintendo.SalmonStage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"image\":"
		out.RawString(prefix)
		out.String(string(in.Image))
	}
	out.RawByte('}')
}
